### Deleting a blog:
DELETE http://localhost:3003/api/blogs/66575bb9bf3e45cc381a77c7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZSBJSSIsImlkIjoiNjViMzE0MWM1ZWU1YTljODEwNGExNzI5IiwiaWF0IjoxNzE3MDAxMjMzfQ.h0aaBYe_5WqC4kcJ537ZvJ-r5wGqWsQHETTjxq9YrDM
### This succesfully deletes the blog!!! (with the correct token)

### Trying to delete a blog as not the blog creator:
DELETE http://localhost:3003/api/blogs/65b7024fac972fda3a3d50d7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QgSUkiLCJpZCI6IjY1YjZkZjg1Yjc0OTVkNDFmNDViZTk3YyIsImlhdCI6MTcwNjQ5MjUyMH0.C2egc_7Vdjr2W54zMEqjohipKPyxQxlNqGBnEuY1f7M
### Here, I got "message": "You are not the creator of the blog!" (Which is what I've been expecting :D)