### Deleting a blog:
DELETE http://localhost:3003/api/blogs/65b6eb0c4ae5f0f61e383ce9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1YjY3Y2I3NjY0OWJhZmI4YTQ1N2EyZCIsImlhdCI6MTcwNjQ4NjM5N30.plsGa-7F2505JVDllgp-owViifXwBkhlmY4pEr6K2FM
### This succesfully deletes the blog!!! (with the correct token)

### Trying to delete a blog as not the blog creator:
DELETE http://localhost:3003/api/blogs/65b6eb0c4ae5f0f61e383ce9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QgSUkiLCJpZCI6IjY1YjZkZjg1Yjc0OTVkNDFmNDViZTk3YyIsImlhdCI6MTcwNjQ4NjU2OH0.6IcfUdzRBz2LQs7Gxjd_TBgDgxt-2ylkJxjX1cPiYn8
### Here, I got "message": "You are not the creator of the blog!" (Which is what I've been expecting :D)