### Posting a new blog:
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Backend is important!",
    "author": "65b3141c5ee5a9c8104a1729",
    "url": "testurl.com",
    "likes": 102
}

### Getting all the data
GET http://localhost:3003/api/blogs