### Posting a new blog:
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "There are relational databases and non-relational databases",
    "author": "Tom Hills",
    "url": "",
    "likes": 1081
}

### Getting all the data
GET http://localhost:3003/api/blogs